extensions:
  opamp:
    server:
      ws:
        endpoint: ws://127.0.0.1:4000/v1/opamp
        tls:
          insecure: true
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  remotetap:
    endpoint: localhost:12001
exporters:
  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [remotetap]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [remotetap]
      exporters: [debug]
    metrics:
      receivers: [prometheus, otlp]
      processors: [remotetap]
      exporters: [debug]
  extensions: [opamp]